package compiler_code;

public enum KeywordType {
	CLASS, METHOD,FUNCITON,
	CONSTRUCTOR, INT,
	BOOLEAN, CHAR, VOID, 
	VAR, STATIC, FIELD, LET,
	DO, IF, ELSE, WHILE,
	RETURN, TRUE, FALSE,
	NULL, THIS
}
